import cruze from "../../assets/cruze.jpeg";
import cruzeInterior from "../../assets/cruzeInterior1.jpeg";
import cruzeBack from "../../assets/cruzeBack.jpeg";

import fordEco from "../../assets/fordEco.jpeg";
import fordEdge from "../../assets/fordEdge.jpeg";
import FordFusion from "../../assets/fordFusion.jpeg";
import fordKuga from "../../assets/fordKuga.jpeg";
import onix from "../../assets/onix.jpeg";
import c3 from "../../assets/citroenC3.jpeg";
import c4 from "../../assets/citroenC4.jpeg";
import cactus from "../../assets/citroenC4Cactus.jpeg";
import peugeot208 from "../../assets/peugeot208.jpeg";
import peugeot2008 from "../../assets/peugeot2008.jpeg";
import gol from "../../assets/vwGol.jpeg";

export const vehiculos = [
  {
    marca: "Chevrolet",
    modelo: "Cruze",
    año: "2024",
    categoria: "Auto",
    tipo: "Automatico",
    conectividad:
      "MyLink: un menú moderno e intuitivo. Usando tu voz podés conversar por mensajes, elegir rutas y acceder a tus playlists. Aprovechá MyLink x2: conectá dos celulares por medio de Bluetooth y dividí la pantalla para ver dos aplicaciones o dispositivos al mismo tiempo.",
    diseño:
      "Además de la parrilla frontal y los detalles cromados, el Cruze 5 también viene con faros traseros en LED, cámara de visión trasera digital, llantas de 17” y techo solar eléctrico. Su interior cuenta con asientos de materiales premium y terminaciones en dos colores: Jet Black y Umber.",
    asistencia:
      "Para evitar que ofusques la visión de otro conductor, un sensor identifica cuando un vehículo se acerca en el sentido contrario al tuyo y disminuye automáticamente la iluminación de tus faros.",
    practicidad:
      "Estacioná sin usar las manos. Easy Park es un sistema de estacionamiento que controla automáticamente los movimientos del volante, por medio de sensores que identifican los lugares, ya sean horizontales o perpendiculares.",
    km: "0",
    precio: "23.000.000",
    img: [cruze, cruzeInterior, cruzeBack],
  },
  {
    marca: "Chevrolet",
    modelo: "Onix",
    año: "2022",
    categoria: "Auto",
    tipo: "Manual",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "28.000",
    precio: "23.000.000",
    img: [onix],
  },
  {
    marca: "Ford",
    modelo: "Fusion",
    año: "2023",
    categoria: "Auto",
    tipo: "Automatico",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "20.000",
    precio: "30.000.000",
    img: [FordFusion],
  },
  {
    marca: "Ford",
    modelo: "Kuga",
    año: "2024",
    categoria: "Camioneta",
    tipo: "Automatico",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "0",
    precio: "22.000.000",
    img: [fordKuga],
  },
  {
    marca: "Ford",
    modelo: "EcoSport",
    año: "2024",
    categoria: "Camioneta",
    tipo: "Automatico",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "0",
    precio: "20.000.000",
    img: [fordEco],
  },
  {
    marca: "Ford",
    modelo: "Edge",
    año: "2021",
    categoria: "Camioneta",
    tipo: "Manual",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "35.000",
    precio: "28.000.000",
    img: [fordEdge],
  },
  {
    marca: "Peugeot",
    modelo: "208",
    año: "2022",
    categoria: "Auto",
    tipo: "Manual",
    km: "25.000",
    precio: "24.000.000",
    img: [peugeot208],
  },
  {
    marca: "Peugeot",
    modelo: "2008",
    año: "2023",
    categoria: "Camioneta",
    tipo: "Automatico",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "20.000",
    precio: "33.000.000",
    img: [peugeot2008],
  },
  {
    marca: "Citroen",
    modelo: "C3",
    año: "2020",
    categoria: "Auto",
    tipo: "Manual",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "32.000",
    precio: "18.000.000",
    img: [c3],
  },
  {
    marca: "Citroen",
    modelo: "C4",
    año: "2021",
    categoria: "Auto",
    tipo: "Automatico",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "",
    precio: "18.000.000",
    img: [c4],
  },
  {
    marca: "Citroen",
    modelo: "C4 Cactus",
    año: "2021",
    categoria: "Auto",
    tipo: "Manual",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "24.000",
    precio: "23.000.000",
    img: [cactus],
  },
  {
    marca: "Volkswagen",
    modelo: "Gol Trend",
    año: "2018",
    categoria: "Auto",
    tipo: "Manual",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "55.000",
    precio: "16.000.000",
    img: [gol],
  },
];
