import cruze from "../../assets/cruze.jpeg";
import fordEco from "../../assets/fordEco.jpeg";
import fordEdge from "../../assets/fordEdge.jpeg";
import FordFusion from "../../assets/fordFusion.jpeg";
import fordKuga from "../../assets/fordKuga.jpeg";
import onix from "../../assets/onix.jpeg";
import c3 from "../../assets/citroenC3.jpeg";
import c4 from "../../assets/citroenC4.jpeg";
import cactus from "../../assets/citroenC4Cactus.jpeg";
import peugeot208 from "../../assets/peugeot208.jpeg";
import peugeot2008 from "../../assets/peugeot2008.jpeg";
import gol from "../../assets/vwGol.jpeg";

export const vehiculos = [
  {
    marca: "Chevrolet",
    modelo: "Cruze",
    categoria: "Auto",
    tipo: "",
    conectividad:"MyLink: un menú moderno e intuitivo. Usando tu voz podés conversar por mensajes, elegir rutas y acceder a tus playlists. Aprovechá MyLink x2: conectá dos celulares por medio de Bluetooth y dividí la pantalla para ver dos aplicaciones o dispositivos al mismo tiempo.",
    diseño: "Además de la parrilla frontal y los detalles cromados, el Cruze 5 también viene con faros traseros en LED, cámara de visión trasera digital, llantas de 17” y techo solar eléctrico. Su interior cuenta con asientos de materiales premium y terminaciones en dos colores: Jet Black y Umber.",
    asistencia: "Para evitar que ofusques la visión de otro conductor, un sensor identifica cuando un vehículo se acerca en el sentido contrario al tuyo y disminuye automáticamente la iluminación de tus faros.",
    practicidad: "Estacioná sin usar las manos. Easy Park es un sistema de estacionamiento que controla automáticamente los movimientos del volante, por medio de sensores que identifican los lugares, ya sean horizontales o perpendiculares.",
    km: "0",
    precio: "23.000.000",
    img: cruze,
  },
  {
    marca: "Chevrolet",
    modelo: "Onix",
    categoria: "Auto",
    tipo: "",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "",
    precio: "23.000.000",
    img: onix,
  },
  {
    marca: "Ford",
    modelo: "Fusion",
    categoria: "Auto",
    tipo: "",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "",
    precio: "30.000.000",
    img: FordFusion,
  },
  {
    marca: "Ford",
    modelo: "Kuga",
    categoria: "Camioneta",
    tipo: "",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "",
    precio: "22.000.000",
    img: fordKuga,
  },
  {
    marca: "Ford",
    modelo: "EcoSport",
    categoria: "Camioneta",
    tipo: "",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "",
    precio: "20.000.000",
    img: fordEco,
  },
  {
    marca: "Ford",
    modelo: "Edge",
    categoria: "Camioneta",
    tipo: "",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "",
    precio: "28.000.000",
    img: fordEdge,
  },
  {
    marca: "Peugeot",
    modelo: "208",
    categoria: "Auto",
    tipo: "",
    km: "",
    precio: "24.000.000",
    img: peugeot208,
  },
  {
    marca: "Peugeot",
    modelo: "2008",
    categoria: "Camioneta",
    tipo: "",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "",
    precio: "33.000.000",
    img: peugeot2008,
  },
  {
    marca: "Citroen",
    modelo: "C3",
    categoria: "Auto",
    tipo: "",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "",
    precio: "18.000.000",
    img: c3,
  },
  {
    marca: "Citroen",
    modelo: "C4",
    categoria: "Auto",
    tipo: "",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "",
    precio: "18.000.000",
    img: c4,
  },
  {
    marca: "Citroen",
    modelo: "C4 Cactus",
    categoria: "Auto",
    tipo: "",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "",
    precio: "23.000.000",
    img: cactus,
  },
  {
    marca: "Volkswagen",
    modelo: "Gol Trend",
    categoria: "Auto",
    tipo: "",
    conectividad: "",
    diseño: "",
    asistencia: "",
    practicidad: "",
    km: "",
    precio: "16.000.000",
    img: gol,
  },
];
